# Generated by Django 5.0.4 on 2024-04-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=100)),
                ('whats_app', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('photo', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grants', models.IntegerField()),
                ('description', models.TextField()),
                ('edu_programs', models.IntegerField()),
                ('demand', models.CharField(max_length=100)),
                ('unis_num', models.IntegerField()),
                ('general', models.IntegerField()),
                ('quota', models.IntegerField()),
                ('photo', models.URLField()),
                ('disciplines', models.ManyToManyField(to='api.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('uni_type', models.CharField(max_length=100)),
                ('grant_score', models.IntegerField()),
                ('paid_score', models.IntegerField()),
                ('address', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('specialties', models.ManyToManyField(to='api.specialty')),
            ],
        ),
    ]
