# Generated by Django 5.0.4 on 2024-04-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_consultant_name_alter_discipline_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='whats_app',
            new_name='whatsApp',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='edu_programs',
            new_name='eduPrograms',
        ),
        migrations.RenameField(
            model_name='specialty',
            old_name='unis_num',
            new_name='unisNum',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='grant_score',
            new_name='grantScore',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='paid_score',
            new_name='paidScore',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='uni_type',
            new_name='uniType',
        ),
    ]
