# Generated by Django 5.0.4 on 2024-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240424_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='eduPrograms',
        ),
        migrations.RemoveField(
            model_name='university',
            name='grantScore',
        ),
        migrations.RemoveField(
            model_name='university',
            name='paidScore',
        ),
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(default='asd', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='code',
            field=models.CharField(default='asd', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default='asd'),
        ),
        migrations.AddField(
            model_name='university',
            name='floorScore',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='university',
            name='link',
            field=models.URLField(default='https://almau.edu.kz/'),
        ),
    ]
