# Generated by Django 5.0.4 on 2024-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240424_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='username',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
