# Generated by Django 5.0.4 on 2024-04-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_specialty_eduprograms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='username',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
