# Generated by Django 5.0.4 on 2024-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('type1', 'Тип 1'), ('type2', 'Тип 2'), ('type3', 'Тип 3')], max_length=20),
        ),
    ]
