# Generated by Django 5.0.4 on 2024-04-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testresult'),
        ('api', '0007_rename_whats_app_consultant_whatsapp_and_more'),
    ]

    operations = [
    ]
